### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by ishandandekar** [ashikshafi08/Recipe1M#1]
Hey, came across this project randomly and found it very interesting, wanted to collaborate in this. Is this project still active?

**Comment by ashikshafi08** [comment]
Hello Ishan. 

Nope, but if you want to check out the nutrify project by Daniel it's quite similar to this one. 
https://github.com/mrdbourke/nutrify

**Comment by ishandandekar** [comment]
Great! Thank you!
